# Generated by Django 5.2.15 on 2026-07-10 12:45

import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Capa do disco ou do livro (JPG, PNG ou WebP).', null=True, upload_to=loja.models.produto_imagem_upload_path),
        ),
    ]
