# Generated by Django 5.2.15 on 2026-07-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseTreinoAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiencia', models.CharField(choices=[('cliente', 'Cliente (loja)'), ('gestor', 'Gestor (painel)')], max_length=10)),
                ('intencao', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frase de treino do assistente',
                'verbose_name_plural': 'Frases de treino do assistente',
                'ordering': ['audiencia', 'intencao', 'texto'],
            },
        ),
    ]
