# Generated by Django 5.2.15 on 2026-08-03 12:28

import django.db.models.deletion
import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_frasetreinoassistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaAudiovisual',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loja.produto')),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('video', 'Vídeo'), ('dvd', 'DVD'), ('bluray', 'Blu-ray')], default='dvd', max_length=20)),
                ('diretor', models.CharField(blank=True, max_length=200)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('duracao_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração (min)')),
            ],
            options={
                'verbose_name': 'Mídia audiovisual',
                'verbose_name_plural': 'Mídias audiovisuais',
            },
            bases=('loja.produto',),
        ),
        migrations.AddField(
            model_name='produto',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Arquivo digital opcional (MP3, FLAC, MP4, MKV, PDF…).', null=True, upload_to=loja.models.produto_arquivo_upload_path),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Capa (JPG, PNG ou WebP).', null=True, upload_to=loja.models.produto_imagem_upload_path),
        ),
    ]
