# Generated by Django 5.2.15 on 2026-08-03 12:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_midia_audiovisual_e_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='dias_aluguel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='modalidade',
            field=models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], default='venda', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='dias_aluguel',
            field=models.PositiveIntegerField(default=7, help_text='Quantidade de dias inclusos no preço do aluguel.', verbose_name='dias de aluguel'),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_aluguel',
            field=models.BooleanField(default=False, verbose_name='disponível para aluguel'),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_venda',
            field=models.BooleanField(default=True, verbose_name='disponível para venda'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_aluguel',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque aluguel'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor cobrado por período de aluguel.', max_digits=10, verbose_name='preço do aluguel'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço de venda'),
        ),
    ]
