# Generated by Django 5.2.15 on 2026-08-03 13:21

import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_ativar_aluguel_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaaudiovisual',
            name='trailer',
            field=models.FileField(blank=True, help_text='Prévia em vídeo do PC (MP4, WebM…).', null=True, upload_to=loja.models.produto_trailer_upload_path, verbose_name='trailer (arquivo)'),
        ),
        migrations.AddField(
            model_name='midiaaudiovisual',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Opcional: link do YouTube ou Vimeo se preferir não enviar arquivo.', verbose_name='trailer (YouTube/Vimeo)'),
        ),
    ]
