# Generated by Django 5.2.15 on 2026-08-17 23:26

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_plano_padrao(apps, schema_editor):
    PlanoClube = apps.get_model('loja', 'PlanoClube')
    if not PlanoClube.objects.exists():
        PlanoClube.objects.create(
            titulo='Clube Vinil & Página',
            descricao=(
                'Curadoria mensal, desconto extra em compras e prioridade em novidades. '
                'Renovação mensal — cancele quando quiser.'
            ),
            preco_mensal=Decimal('29.90'),
            desconto_extra_percent=5,
            ativo=True,
            ordem=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_extra_percent', models.PositiveIntegerField(default=5, help_text='Desconto adicional em compras (%) para assinantes.')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano do clube',
                'verbose_name_plural': 'Planos do clube',
                'ordering': ['ordem', 'preco_mensal'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descontos de combo, clube etc.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plano_clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='loja.planoclube'),
        ),
        migrations.CreateModel(
            name='AssinaturaClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('valido_ate', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_clube', to='loja.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_clube', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='loja.planoclube')),
            ],
            options={
                'verbose_name': 'Assinatura do clube',
                'verbose_name_plural': 'Assinaturas do clube',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'plano'), name='uniq_assinatura_usuario_plano')],
            },
        ),
        migrations.RunPython(criar_plano_padrao, migrations.RunPython.noop),
    ]
