# Generated by Django 5.2.15 on 2026-10-08 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_media_path_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaaudiovisual',
            name='filme_url',
            field=models.URLField(blank=True, help_text='YouTube não listado, Vimeo ou Google Drive. Só quem pagou para assistir vê.', max_length=500, verbose_name='link do filme completo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome de quem recebe'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='estado (UF)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_assistir',
            field=models.BooleanField(default=False, verbose_name='disponível para assistir online'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_assistir',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor cobrado para assistir o filme online.', max_digits=10, verbose_name='preço para assistir'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='modalidade',
            field=models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('assistir', 'Assistir online')], default='venda', max_length=20),
        ),
    ]
