# Generated by Django 5.2.15 on 2026-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_filmes_assistir_e_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('telefone', 'Celular'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], max_length=10, verbose_name='tipo da chave')),
                ('chave', models.CharField(max_length=77, verbose_name='chave Pix')),
                ('nome_recebedor', models.CharField(help_text='Como aparece no banco do cliente. Até 25 letras.', max_length=25, verbose_name='nome de quem recebe')),
                ('cidade', models.CharField(help_text='Até 15 letras.', max_length=15, verbose_name='cidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pix da loja',
                'verbose_name_plural': 'Pix da loja',
            },
        ),
    ]
