# Generated by Django 5.2.15 on 2026-10-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_pix_da_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=60, verbose_name='código de rastreio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='link_rastreio',
            field=models.URLField(blank=True, max_length=500, verbose_name='link de rastreio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_entrega',
            field=models.CharField(blank=True, choices=[('preparando', 'Preparando o envio'), ('enviado', 'Enviado'), ('saiu_para_entrega', 'Saiu para entrega'), ('entregue', 'Entregue')], max_length=20, verbose_name='andamento da entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='loja.pedido')),
            ],
            options={
                'ordering': ['criado_em', 'pk'],
            },
        ),
    ]
