# Generated by Django 5.2.15 on 2026-10-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_acompanhar_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='removido_da_biblioteca',
            field=models.BooleanField(default=False, verbose_name='removido da biblioteca pelo cliente'),
        ),
    ]
